/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TryOnRouteImport } from './routes/try-on'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SalonConfigRouteImport } from './routes/salon-config'
import { Route as MyLooksRouteImport } from './routes/my-looks'
import { Route as LashLabRouteImport } from './routes/lash-lab'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as IndexRouteImport } from './routes/index'

const TryOnRoute = TryOnRouteImport.update({
  id: '/try-on',
  path: '/try-on',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SalonConfigRoute = SalonConfigRouteImport.update({
  id: '/salon-config',
  path: '/salon-config',
  getParentRoute: () => rootRouteImport,
} as any)
const MyLooksRoute = MyLooksRouteImport.update({
  id: '/my-looks',
  path: '/my-looks',
  getParentRoute: () => rootRouteImport,
} as any)
const LashLabRoute = LashLabRouteImport.update({
  id: '/lash-lab',
  path: '/lash-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/booking': typeof BookingRoute
  '/gallery': typeof GalleryRoute
  '/lash-lab': typeof LashLabRoute
  '/my-looks': typeof MyLooksRoute
  '/salon-config': typeof SalonConfigRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/try-on': typeof TryOnRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/booking': typeof BookingRoute
  '/gallery': typeof GalleryRoute
  '/lash-lab': typeof LashLabRoute
  '/my-looks': typeof MyLooksRoute
  '/salon-config': typeof SalonConfigRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/try-on': typeof TryOnRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/booking': typeof BookingRoute
  '/gallery': typeof GalleryRoute
  '/lash-lab': typeof LashLabRoute
  '/my-looks': typeof MyLooksRoute
  '/salon-config': typeof SalonConfigRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/try-on': typeof TryOnRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/booking'
    | '/gallery'
    | '/lash-lab'
    | '/my-looks'
    | '/salon-config'
    | '/sitemap.xml'
    | '/try-on'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/booking'
    | '/gallery'
    | '/lash-lab'
    | '/my-looks'
    | '/salon-config'
    | '/sitemap.xml'
    | '/try-on'
  id:
    | '__root__'
    | '/'
    | '/booking'
    | '/gallery'
    | '/lash-lab'
    | '/my-looks'
    | '/salon-config'
    | '/sitemap.xml'
    | '/try-on'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookingRoute: typeof BookingRoute
  GalleryRoute: typeof GalleryRoute
  LashLabRoute: typeof LashLabRoute
  MyLooksRoute: typeof MyLooksRoute
  SalonConfigRoute: typeof SalonConfigRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TryOnRoute: typeof TryOnRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/try-on': {
      id: '/try-on'
      path: '/try-on'
      fullPath: '/try-on'
      preLoaderRoute: typeof TryOnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salon-config': {
      id: '/salon-config'
      path: '/salon-config'
      fullPath: '/salon-config'
      preLoaderRoute: typeof SalonConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-looks': {
      id: '/my-looks'
      path: '/my-looks'
      fullPath: '/my-looks'
      preLoaderRoute: typeof MyLooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lash-lab': {
      id: '/lash-lab'
      path: '/lash-lab'
      fullPath: '/lash-lab'
      preLoaderRoute: typeof LashLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookingRoute: BookingRoute,
  GalleryRoute: GalleryRoute,
  LashLabRoute: LashLabRoute,
  MyLooksRoute: MyLooksRoute,
  SalonConfigRoute: SalonConfigRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TryOnRoute: TryOnRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
